# Generated by Django 5.2.7 on 2025-11-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_module_options_content_order_module_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='course',
            name='images',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
