# Generated by Django 5.2.7 on 2025-11-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_duration_course_images_course_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='images',
            new_name='image',
        ),
    ]
